In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib_inline as mlt

In [2]:
df=pd.read_csv('Merged_True_False.csv')
df.head()

,title,text,subject,date,Label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1

In [3]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [4]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /home/studio-lab-
[nltk_data]     user/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /home/studio-lab-
[nltk_data]     user/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [4]:
import re

In [6]:
lemmatizer = WordNetLemmatizer()
def lammatize_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)
    words = text.split()
    lammatized_words=[lemmatizer.lemmatize(word) for word in words if word not in stopwords.words('english')]
    return " ".join(lammatized_words)

In [7]:
df['title'] = df['title'].apply(lammatize_text)
df.head()

,title,text,subject,date,Label
0,u budget fight loom republican flip fiscal script,WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,u military accept transgender recruit monday p...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,senior u republican senator let mr mueller job,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,fbi russia probe helped australian diplomat ti...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,trump want postal service charge much amazon s...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1

In [8]:
df['text'] = df['text'].apply(lammatize_text)
df.head()

,title,text,subject,date,Label
0,u budget fight loom republican flip fiscal script,washington reuters head conservative republica...,politicsNews,"December 31, 2017",1
1,u military accept transgender recruit monday p...,washington reuters transgender people allowed ...,politicsNews,"December 29, 2017",1
2,senior u republican senator let mr mueller job,washington reuters special counsel investigati...,politicsNews,"December 31, 2017",1
3,fbi russia probe helped australian diplomat ti...,washington reuters trump campaign adviser geor...,politicsNews,"December 30, 2017",1
4,trump want postal service charge much amazon s...,seattlewashington reuters president donald tru...,politicsNews,"December 29, 2017",1

In [2]:
df=pd.read_csv('Dataset.csv')
df.head()

,title,text,subject,date,Label
0,u budget fight loom republican flip fiscal script,washington reuters head conservative republica...,politicsNews,"December 31, 2017",1
1,u military accept transgender recruit monday p...,washington reuters transgender people allowed ...,politicsNews,"December 29, 2017",1
2,senior u republican senator let mr mueller job,washington reuters special counsel investigati...,politicsNews,"December 31, 2017",1
3,fbi russia probe helped australian diplomat ti...,washington reuters trump campaign adviser geor...,politicsNews,"December 30, 2017",1
4,trump want postal service charge much amazon s...,seattlewashington reuters president donald tru...,politicsNews,"December 29, 2017",1

In [3]:
df['subject']=df['subject'].replace('politics','politicsNews')

In [4]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

2025-10-16 17:33:29.126592: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [5]:
df=df.drop('date',axis=1)

In [6]:
y=df['Label']
X=df.drop(columns='Label',axis=1)

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [8]:
VOCAB_SIZE = 25000
TITLE_MAX_LENGTH = 100
TEXT_MAX_LENGTH = 1500

In [9]:
all_texts = pd.concat([X_train['title'], X_train['text']], ignore_index=True).astype(str)
tokenizer = Tokenizer(num_words=VOCAB_SIZE, oov_token="<OOV>")
tokenizer.fit_on_texts(all_texts)

In [10]:
def process_text_with_tokenizer(text_series, tokenizer, max_length):
    """
    Takes a pandas Series of text, a fitted tokenizer, and a max length,
    and returns padded integer sequences.
    """
    # a. Convert texts to sequences of integers
    sequences = tokenizer.texts_to_sequences(text_series.astype(str))
    
    # b. Pad the sequences to a uniform length
    padded_sequences = pad_sequences(
        sequences,
        maxlen=max_length,
        padding='post',
        truncating='post'
    )
    return padded_sequences

In [11]:
padded_title_sequences = process_text_with_tokenizer(X_train['title'], tokenizer, TITLE_MAX_LENGTH)
X_train['title_vectors'] = list(padded_title_sequences)

In [12]:
padded_text_sequences = process_text_with_tokenizer(X_train['text'], tokenizer, TEXT_MAX_LENGTH)
X_train['text_vectors'] = list(padded_text_sequences)

In [13]:
padded_title_sequences = process_text_with_tokenizer(X_test['title'], tokenizer, TITLE_MAX_LENGTH)
X_test['title_vectors'] = list(padded_title_sequences)

In [14]:
padded_text_sequences = process_text_with_tokenizer(X_test['text'], tokenizer, TEXT_MAX_LENGTH)
X_test['text_vectors'] = list(padded_text_sequences)

In [15]:
X_train.head()

,title,text,subject,title_vectors,text_vectors
41287,powerful formerly oppressed ex muslim warns ig...,former muslim donald trump supporter fled isla...,left-news,"[922, 4493, 8499, 12294, 132, 3687, 3736, 26, ...","[42, 132, 19, 2, 169, 2057, 1, 4956, 11, 441, ..."
37838,gary johnson meet creepy proamnesty antigun pr...,anyone belief conservative average trump suppo...,Government News,"[3038, 909, 503, 5095, 19268, 9428, 1, 12891, ...","[418, 685, 134, 1440, 2, 169, 1437, 47, 4551, ..."
14593,u say take step cambodia dissolve opposition p...,washington reuters united state expressed grav...,worldnews,"[4, 16, 70, 437, 3144, 9560, 336, 27, 0, 0, 0,...","[43, 18, 28, 5, 1032, 3930, 320, 137, 6633, 17..."
8019,prairie white house inside tribe quest stop pi...,cannon ball ndwashington reuters three day gua...,politicsNews,"[20368, 23, 15, 917, 3780, 5867, 278, 2174, 0,...","[7850, 2551, 1, 18, 158, 48, 1218, 2086, 1093,..."
35649,obama race set gitmo terrorist freeleaves serv...,hard imagine president could antiamerican prot...,politicsNews,"[21, 341, 269, 5535, 319, 1, 9036, 4257, 292, ...","[488, 2155, 7, 25, 4598, 1, 257, 3742, 21, 972..."

In [16]:
X_train=X_train.drop(columns=['title','text'],axis=1)

In [17]:
X_test=X_test.drop(columns=['title','text'],axis=1)

In [18]:
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder(sparse_output=False)

In [19]:
enco_train=encoder.fit_transform(X_train[['subject']])
new_column_names = encoder.get_feature_names_out(['subject'])
encoded_df = pd.DataFrame(
    enco_train,
    columns=new_column_names,
    index=X_train.index
)
X_train = pd.concat([X_train.drop('subject', axis=1), encoded_df], axis=1)

In [20]:
enco_test=encoder.transform(X_test[['subject']])
new_column_names_test = encoder.get_feature_names_out(['subject'])
encoded_df = pd.DataFrame(
    enco_test,
    columns=new_column_names,
    index=X_test.index 
)
X_test = pd.concat([X_test.drop('subject', axis=1), encoded_df], axis=1)

In [21]:
import pickle
with open('encoder.pkl','wb') as file:
    pickle.dump(encoder,file)

In [22]:
import pickle
with open('tokenizer.pkl','wb') as file:
    pickle.dump(tokenizer,file)

In [23]:
X_train.head()

,title_vectors,text_vectors,subject_Government News,subject_Middle-east,subject_News,subject_US_News,subject_left-news,subject_politicsNews,subject_worldnews
41287,"[922, 4493, 8499, 12294, 132, 3687, 3736, 26, ...","[42, 132, 19, 2, 169, 2057, 1, 4956, 11, 441, ...",0.0,0.0,0.0,0.0,1.0,0.0,0.0
37838,"[3038, 909, 503, 5095, 19268, 9428, 1, 12891, ...","[418, 685, 134, 1440, 2, 169, 1437, 47, 4551, ...",1.0,0.0,0.0,0.0,0.0,0.0,0.0
14593,"[4, 16, 70, 437, 3144, 9560, 336, 27, 0, 0, 0,...","[43, 18, 28, 5, 1032, 3930, 320, 137, 6633, 17...",0.0,0.0,0.0,0.0,0.0,0.0,1.0
8019,"[20368, 23, 15, 917, 3780, 5867, 278, 2174, 0,...","[7850, 2551, 1, 18, 158, 48, 1218, 2086, 1093,...",0.0,0.0,0.0,0.0,0.0,1.0,0.0
35649,"[21, 341, 269, 5535, 319, 1, 9036, 4257, 292, ...","[488, 2155, 7, 25, 4598, 1, 257, 3742, 21, 972...",0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [24]:

import os
output_folder = 'processed_data'
os.makedirs(output_folder, exist_ok=True)

X_train.to_csv(os.path.join(output_folder, 'X_train_processed.csv'), index=False)
X_test.to_csv(os.path.join(output_folder, 'X_test_processed.csv'), index=False)
y_train.to_csv(os.path.join(output_folder, 'y_train.csv'), index=False)
y_test.to_csv(os.path.join(output_folder, 'y_test.csv'), index=False)

In [25]:
def parse_vector_list(vector_list):
    """Convert list of arrays to 2D numpy array"""
    return np.array(vector_list)

# Extract vectors
X_train_title_vectors = np.array(X_train['title_vectors'].tolist())
X_train_text_vectors = np.array(X_train['text_vectors'].tolist())
X_test_title_vectors = np.array(X_test['title_vectors'].tolist())
X_test_text_vectors = np.array(X_test['text_vectors'].tolist())

# Get other features (without vectors)
X_train_other = X_train.drop(columns=['title_vectors', 'text_vectors']).values
X_test_other = X_test.drop(columns=['title_vectors', 'text_vectors']).values

# Save as numpy files
np.save('processed_data/X_train_title.npy', X_train_title_vectors)
np.save('processed_data/X_train_text.npy', X_train_text_vectors)
np.save('processed_data/X_train_other.npy', X_train_other)

np.save('processed_data/X_test_title.npy', X_test_title_vectors)
np.save('processed_data/X_test_text.npy', X_test_text_vectors)
np.save('processed_data/X_test_other.npy', X_test_other)

np.save('processed_data/y_train.npy', y_train.values)
np.save('processed_data/y_test.npy', y_test.values)

print("✓ Data saved as numpy arrays")
print(f"X_train_title shape: {X_train_title_vectors.shape}")
print(f"X_train_text shape: {X_train_text_vectors.shape}")
print(f"X_train_other shape: {X_train_other.shape}")

✓ Data saved as numpy arrays
X_train_title shape: (35918, 100)
X_train_text shape: (35918, 1500)
X_train_other shape: (35918, 7)